package msgp

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Uint128) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	z.Low, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "Low")
		return
	}
	z.High, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "High")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Uint128) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Low)
	if err != nil {
		err = msgp.WrapError(err, "Low")
		return
	}
	err = en.WriteUint64(z.High)
	if err != nil {
		err = msgp.WrapError(err, "High")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Uint128) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	o = msgp.AppendUint64(o, z.Low)
	o = msgp.AppendUint64(o, z.High)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Uint128) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	z.Low, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Low")
		return
	}
	z.High, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "High")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Uint128) Msgsize() (s int) {
	s = 1 + msgp.Uint64Size + msgp.Uint64Size
	return
}
